import {
  Exam,
  Company,
  DSAProblem,
  DataScienceTopic,
  WebDevTopic,
  ProjectTask,
  ProjectMilestone,
  ClientProject,
  Habit,
  CalendarEvent,
  Task,
  LTQuestionLog,
  TimeSession,
} from '../types';

export const INITIAL_EXAMS: Exam[] = [
  {
    id: 'exam-pw',
    name: 'Physics Wallah',
    type: 'Placement / Teaching Staff',
    date: '2026-10-03',
    priority: 'critical',
    companyOrCourse: 'Physics Wallah',
    description: 'Recruitment test for Teaching Staff / Content Expert role.',
    status: 'upcoming',
    preparednessPercent: 75,
    syllabus: ['Physics Core Concepts', 'Pedagogy & Problem Explanation', 'Aptitude', 'Subject Knowledge Test'],
  },
  {
    id: 'exam-ce1',
    name: 'Course Exam 1',
    type: 'Academic Exam',
    date: '2026-10-05',
    priority: 'critical',
    companyOrCourse: 'MTech Semester 3',
    description: 'Core Data Science Theory & Statistical Inference Examination.',
    status: 'upcoming',
    preparednessPercent: 60,
    syllabus: ['Statistical Inference', 'Hypothesis Testing', 'Regression Modeling', 'Multivariate Analysis'],
  },
  {
    id: 'exam-ce2',
    name: 'Course Exam 2',
    type: 'Academic Exam',
    date: '2026-10-07',
    priority: 'critical',
    companyOrCourse: 'MTech Semester 3',
    description: 'Advanced Machine Learning & Deep Learning Architectures.',
    status: 'upcoming',
    preparednessPercent: 55,
    syllabus: ['Neural Networks', 'Optimization Algorithms', 'CNN & Sequence Models', 'Clustering & Ensembles'],
  },
  {
    id: 'exam-lt',
    name: 'L&T Placement Exam',
    type: 'Placement Exam',
    date: '2026-10-12',
    priority: 'critical',
    companyOrCourse: 'Larsen & Toubro',
    description: 'Comprehensive campus placement test: Quantitative, Logical, Verbal & Technical rounds.',
    status: 'upcoming',
    preparednessPercent: 65,
    syllabus: ['Quantitative Aptitude', 'Logical Reasoning', 'Verbal Ability', 'Core Technical & DS/ML'],
  },
  {
    id: 'exam-mooc',
    name: 'MOOCs Exam',
    type: 'Academic Exam',
    date: '2026-10-16',
    priority: 'critical',
    companyOrCourse: 'NPTEL / Swayam Online Course',
    description: 'Proctored semester credit completion certification exam.',
    status: 'upcoming',
    preparednessPercent: 50,
    syllabus: ['All 12 Modules of Swayam Course', 'Past 5 Year Question Papers', 'Weekly Assignment Quizzes'],
  },
];

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'comp-pw',
    name: 'Physics Wallah',
    role: 'Teaching Staff / Subject Expert',
    status: 'Exam Scheduled',
    applicationDate: '2026-09-18',
    examDate: '2026-10-03',
    packageLPA: '12 - 16 LPA',
    location: 'Noida / Remote',
    notes: 'Focus on clear conceptual communication and quick numerical solving.',
  },
  {
    id: 'comp-lt',
    name: 'Larsen & Toubro (L&T)',
    role: 'Graduate Engineer / Data Analyst',
    status: 'Exam Scheduled',
    applicationDate: '2026-09-20',
    examDate: '2026-10-12',
    packageLPA: '9.5 - 14 LPA',
    location: 'Mumbai / Bangalore',
    notes: 'Aptitude accuracy speed is key; revise SQL, Python and probability.',
  },
  {
    id: 'comp-ba',
    name: 'Black Apple',
    role: 'Software Intern',
    status: 'Preparing',
    applicationDate: '2026-09-22',
    examDate: undefined,
    packageLPA: 'Stipend ₹45k/mo',
    location: 'Bangalore / Hybrid',
    notes: 'Date status: TBD. Prepare full-stack portfolio and LeetCode Mediums.',
  },
  {
    id: 'comp-google',
    name: 'Google',
    role: 'Software Engineer - University Grad',
    status: 'Interested',
    applicationDate: '2026-09-25',
    packageLPA: '35+ LPA',
    location: 'Bangalore / Hyderabad',
    notes: 'Target for Jan 2027 placement cycle. Complete Striver SDE sheet and Graphs/DP.',
  },
  {
    id: 'comp-ms',
    name: 'Microsoft',
    role: 'Data & Applied Scientist',
    status: 'Interested',
    packageLPA: '28+ LPA',
    location: 'Hyderabad',
    notes: 'Strong ML fundamentals + LeetCode Medium/Hard proficiency needed.',
  },
];

export const INITIAL_DSA_TOPICS = [
  'Arrays',
  'Strings',
  'Hashing',
  'Two Pointers',
  'Sliding Window',
  'Binary Search',
  'Linked List',
  'Stack',
  'Queue',
  'Recursion',
  'Backtracking',
  'Trees',
  'BST',
  'Heap',
  'Graphs',
  'Greedy',
  'Dynamic Programming',
];

export const INITIAL_DSA_PROBLEMS: DSAProblem[] = [
  {
    id: 'dsa-1',
    title: 'Two Sum',
    topic: 'Arrays',
    platform: 'LeetCode',
    difficulty: 'Easy',
    status: 'Solved',
    timeTakenMinutes: 12,
    attempts: 1,
    solved: true,
    revisionRequired: false,
    notes: 'Optimal solution using Hash Map with O(n) time and O(n) space.',
    url: 'https://leetcode.com/problems/two-sum/',
    lastPracticed: '2026-09-24',
  },
  {
    id: 'dsa-2',
    title: '3Sum',
    topic: 'Two Pointers',
    platform: 'LeetCode',
    difficulty: 'Medium',
    status: 'Solved',
    timeTakenMinutes: 28,
    attempts: 2,
    solved: true,
    revisionRequired: true,
    notes: 'Sort array first. Avoid duplicates by skipping equal adjacent values.',
    url: 'https://leetcode.com/problems/3sum/',
    lastPracticed: '2026-09-25',
  },
  {
    id: 'dsa-3',
    title: 'Longest Substring Without Repeating Characters',
    topic: 'Sliding Window',
    platform: 'LeetCode',
    difficulty: 'Medium',
    status: 'Solved',
    timeTakenMinutes: 22,
    attempts: 1,
    solved: true,
    revisionRequired: false,
    notes: 'Sliding window with character index map to jump left pointer.',
    url: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
    lastPracticed: '2026-09-26',
  },
  {
    id: 'dsa-4',
    title: 'Trapping Rain Water',
    topic: 'Two Pointers',
    platform: 'LeetCode',
    difficulty: 'Hard',
    status: 'Revision Required',
    timeTakenMinutes: 45,
    attempts: 3,
    solved: true,
    revisionRequired: true,
    notes: 'Two pointer approach with leftMax and rightMax is O(1) space. Revise pointer movement logic.',
    url: 'https://leetcode.com/problems/trapping-rain-water/',
    lastPracticed: '2026-09-23',
  },
  {
    id: 'dsa-5',
    title: 'LRU Cache',
    topic: 'Linked List',
    platform: 'LeetCode',
    difficulty: 'Medium',
    status: 'Solved',
    timeTakenMinutes: 35,
    attempts: 2,
    solved: true,
    revisionRequired: true,
    notes: 'Doubly Linked List + Hash Map for O(1) get and put.',
    url: 'https://leetcode.com/problems/lru-cache/',
    lastPracticed: '2026-09-22',
  },
  {
    id: 'dsa-6',
    title: 'Binary Tree Level Order Traversal',
    topic: 'Trees',
    platform: 'LeetCode',
    difficulty: 'Medium',
    status: 'Solved',
    timeTakenMinutes: 18,
    attempts: 1,
    solved: true,
    revisionRequired: false,
    notes: 'Queue BFS approach keeping track of level size.',
    url: 'https://leetcode.com/problems/binary-tree-level-order-traversal/',
    lastPracticed: '2026-09-21',
  },
  {
    id: 'dsa-7',
    title: 'Course Schedule (Cycle Detection)',
    topic: 'Graphs',
    platform: 'LeetCode',
    difficulty: 'Medium',
    status: 'In Progress',
    timeTakenMinutes: 30,
    attempts: 1,
    solved: false,
    revisionRequired: true,
    notes: 'Kahn algorithm (topological sort with in-degrees) or DFS with visited array.',
    url: 'https://leetcode.com/problems/course-schedule/',
    lastPracticed: '2026-09-26',
  },
  {
    id: 'dsa-8',
    title: '0/1 Knapsack Problem',
    topic: 'Dynamic Programming',
    platform: 'GeeksforGeeks',
    difficulty: 'Medium',
    status: 'Solved',
    timeTakenMinutes: 25,
    attempts: 1,
    solved: true,
    revisionRequired: false,
    notes: 'Standard 2D DP memoization and bottom-up space-optimized to 1D array.',
    url: 'https://www.geeksforgeeks.org/0-1-knapsack-problem-dp-10/',
    lastPracticed: '2026-09-20',
  },
  {
    id: 'dsa-9',
    title: 'Longest Increasing Subsequence',
    topic: 'Dynamic Programming',
    platform: 'LeetCode',
    difficulty: 'Medium',
    status: 'Not Started',
    solved: false,
    revisionRequired: false,
    url: 'https://leetcode.com/problems/longest-increasing-subsequence/',
  },
  {
    id: 'dsa-10',
    title: 'Median of Two Sorted Arrays',
    topic: 'Binary Search',
    platform: 'LeetCode',
    difficulty: 'Hard',
    status: 'Not Started',
    solved: false,
    revisionRequired: false,
    url: 'https://leetcode.com/problems/median-of-two-sorted-arrays/',
  },
];

export const INITIAL_DATA_SCIENCE_TOPICS: DataScienceTopic[] = [
  { id: 'ds-1', name: 'Python', status: 'Completed', hoursSpent: 30, notesCompleted: true, projectsCompleted: 4, keyConcepts: ['OOP', 'Generators', 'Decorators', 'Type Hinting'] },
  { id: 'ds-2', name: 'NumPy', status: 'Completed', hoursSpent: 16, notesCompleted: true, projectsCompleted: 3, keyConcepts: ['Vectorization', 'Broadcasting', 'Indexing', 'Linear Algebra'] },
  { id: 'ds-3', name: 'Pandas', status: 'Completed', hoursSpent: 28, notesCompleted: true, projectsCompleted: 5, keyConcepts: ['DataFrames', 'GroupBy', 'Pivot Tables', 'Time Series'] },
  { id: 'ds-4', name: 'Matplotlib & Seaborn', status: 'Completed', hoursSpent: 14, notesCompleted: true, projectsCompleted: 4, keyConcepts: ['Subplots', 'Histograms', 'Heatmaps', 'Pairplots'] },
  { id: 'ds-5', name: 'Statistics', status: 'Practicing', hoursSpent: 22, notesCompleted: true, projectsCompleted: 2, keyConcepts: ['Descriptive', 'Inferential', 'Distributions', 'Central Limit Theorem'] },
  { id: 'ds-6', name: 'Probability', status: 'Practicing', hoursSpent: 18, notesCompleted: true, projectsCompleted: 2, keyConcepts: ['Bayes Theorem', 'Conditional Probability', 'Random Variables'] },
  { id: 'ds-7', name: 'Exploratory Data Analysis (EDA)', status: 'Completed', hoursSpent: 20, notesCompleted: true, projectsCompleted: 4, keyConcepts: ['Outlier Detection', 'Imputation', 'Feature Correlation'] },
  { id: 'ds-8', name: 'SQL', status: 'Completed', hoursSpent: 24, notesCompleted: true, projectsCompleted: 3, keyConcepts: ['Window Functions', 'Joins', 'CTEs', 'Indexing & Aggregations'] },
  { id: 'ds-9', name: 'Machine Learning Fundamentals', status: 'Practicing', hoursSpent: 25, notesCompleted: true, projectsCompleted: 3, keyConcepts: ['Bias-Variance Tradeoff', 'Cross Validation', 'Regularization'] },
  { id: 'ds-10', name: 'Supervised Learning', status: 'Practicing', hoursSpent: 30, notesCompleted: true, projectsCompleted: 3, keyConcepts: ['Linear/Logistic Reg', 'Decision Trees', 'Random Forests', 'XGBoost'] },
  { id: 'ds-11', name: 'Unsupervised Learning', status: 'Learning', hoursSpent: 12, notesCompleted: false, projectsCompleted: 1, keyConcepts: ['K-Means', 'Hierarchical', 'DBSCAN', 'Anomaly Detection'] },
  { id: 'ds-12', name: 'Feature Engineering', status: 'Practicing', hoursSpent: 15, notesCompleted: true, projectsCompleted: 2, keyConcepts: ['Scaling', 'One-Hot/Target Encoding', 'Binning'] },
  { id: 'ds-13', name: 'PCA & Dimensionality Reduction', status: 'Learning', hoursSpent: 8, notesCompleted: false, projectsCompleted: 1, keyConcepts: ['Eigenvectors', 'SVD', 'Variance Ratio', 't-SNE'] },
  { id: 'ds-14', name: 'Model Evaluation & Metrics', status: 'Practicing', hoursSpent: 14, notesCompleted: true, projectsCompleted: 2, keyConcepts: ['ROC-AUC', 'Precision-Recall', 'Confusion Matrix', 'F1-Score'] },
  { id: 'ds-15', name: 'Deep Learning', status: 'Learning', hoursSpent: 18, notesCompleted: false, projectsCompleted: 1, keyConcepts: ['Backprop', 'Activation Functions', 'Optimizers (Adam)', 'PyTorch'] },
  { id: 'ds-16', name: 'Natural Language Processing (NLP)', status: 'Not Started', hoursSpent: 0, notesCompleted: false, projectsCompleted: 0, keyConcepts: ['Tokenization', 'TF-IDF', 'Word2Vec', 'Transformers', 'BERT'] },
  { id: 'ds-17', name: 'Retrieval-Augmented Generation (RAG)', status: 'Not Started', hoursSpent: 0, notesCompleted: false, projectsCompleted: 0, keyConcepts: ['Vector Databases', 'LangChain', 'Embedding Search', 'Chunking'] },
];

export const INITIAL_WEB_DEV_TOPICS: WebDevTopic[] = [
  { id: 'wd-1', name: 'HTML5 & Semantic Markup', status: 'Completed', hoursSpent: 10, notesCompleted: true, keyConcepts: ['Semantic tags', 'Accessibility (a11y)', 'SEO Meta Tags'] },
  { id: 'wd-2', name: 'Modern CSS & Flexbox/Grid', status: 'Completed', hoursSpent: 20, notesCompleted: true, keyConcepts: ['Flexbox', 'CSS Grid', 'Custom Properties', 'Animations', 'Tailwind'] },
  { id: 'wd-3', name: 'JavaScript ES6+', status: 'Completed', hoursSpent: 35, notesCompleted: true, keyConcepts: ['Closures', 'Promises / Async Await', 'Event Loop', 'Prototypes'] },
  { id: 'wd-4', name: 'React (Hooks & State)', status: 'Completed', hoursSpent: 40, notesCompleted: true, keyConcepts: ['useEffect', 'useMemo', 'Custom Hooks', 'Context API', 'State Modeling'] },
  { id: 'wd-5', name: 'Next.js App Router', status: 'Completed', hoursSpent: 30, notesCompleted: true, keyConcepts: ['Server Components', 'Server Actions', 'SSR/SSG', 'Route Handlers'] },
  { id: 'wd-6', name: 'Node.js & Express', status: 'Practicing', hoursSpent: 22, notesCompleted: true, keyConcepts: ['Middleware', 'REST Architecture', 'Event Emitter', 'Streams'] },
  { id: 'wd-7', name: 'MongoDB & Mongoose', status: 'Practicing', hoursSpent: 18, notesCompleted: true, keyConcepts: ['Aggregation Pipelines', 'Schema Design', 'Indexes'] },
  { id: 'wd-8', name: 'REST APIs & Security', status: 'Practicing', hoursSpent: 15, notesCompleted: true, keyConcepts: ['JWT Auth', 'CORS', 'Rate Limiting', 'Sanitization'] },
  { id: 'wd-9', name: 'Git & GitHub Workflows', status: 'Completed', hoursSpent: 15, notesCompleted: true, keyConcepts: ['Branching', 'Rebase vs Merge', 'Pull Requests', 'Actions CI/CD'] },
  { id: 'wd-10', name: 'TypeScript', status: 'Practicing', hoursSpent: 25, notesCompleted: true, keyConcepts: ['Generics', 'Utility Types', 'Strict Typing', 'Inference'] },
  { id: 'wd-11', name: 'Database ORM (Prisma/Drizzle)', status: 'Practicing', hoursSpent: 12, notesCompleted: true, keyConcepts: ['Schema Migrations', 'Relations', 'Query Optimizations'] },
  { id: 'wd-12', name: 'Deployment & Cloud (Vercel, Docker)', status: 'Practicing', hoursSpent: 10, notesCompleted: true, keyConcepts: ['CI/CD Pipelines', 'Environment Config', 'Dockerizing Apps'] },
];

export const INITIAL_PROJECT_MILESTONES: ProjectMilestone[] = [
  { id: 'pm-1', title: 'Research & Literature Review', order: 1, status: 'Completed', targetDate: '2026-10-05', description: 'Survey state-of-the-art papers in applied multimodal AI.' },
  { id: 'pm-2', title: 'Problem Definition & Architecture', order: 2, status: 'Completed', targetDate: '2026-10-10', description: 'Define core deliverables and technical system architecture.' },
  { id: 'pm-3', title: 'Dataset Collection & Curation', order: 3, status: 'In Progress', targetDate: '2026-10-18', description: 'Collect and clean 50,000+ domain specific samples.' },
  { id: 'pm-4', title: 'Data Preprocessing & Augmentation', order: 4, status: 'In Progress', targetDate: '2026-10-25', description: 'Build pipeline for tokenization, normalization, and feature extraction.' },
  { id: 'pm-5', title: 'Baseline Model Implementation', order: 5, status: 'Pending', targetDate: '2026-11-02', description: 'Train baseline models for benchmark comparison.' },
  { id: 'pm-6', title: 'Advanced Architecture Experimentation', order: 6, status: 'Pending', targetDate: '2026-11-10', description: 'Train fine-tuned Transformer / hybrid deep model.' },
  { id: 'pm-7', title: 'Model Evaluation & Ablation Study', order: 7, status: 'Pending', targetDate: '2026-11-17', description: 'Measure Precision, Recall, F1, latency, and ablation insights.' },
  { id: 'pm-8', title: 'Interactive Web Dashboard & API', order: 8, status: 'Pending', targetDate: '2026-11-22', description: 'Build user-facing prototype demo interface.' },
  { id: 'pm-9', title: 'Thesis Documentation & Report', order: 9, status: 'Pending', targetDate: '2026-11-25', description: 'Draft comprehensive 60-page final academic thesis.' },
  { id: 'pm-10', title: 'Final Defense Presentation', order: 10, status: 'Pending', targetDate: '2026-11-27', description: 'Slide deck preparation and mock viva defense.' },
];

export const INITIAL_PROJECT_TASKS: ProjectTask[] = [
  {
    id: 'pt-1',
    title: 'Survey 15 Key Papers on Multimodal Embeddings',
    description: 'Summarize comparative metrics, datasets used, and limitations.',
    priority: 'high',
    deadline: '2026-10-02',
    estimatedHours: 8,
    actualHours: 8,
    status: 'Completed',
    notes: 'Completed summary table in Notion.',
  },
  {
    id: 'pt-2',
    title: 'Download and Parse Kaggle / Open Source Dataset',
    description: 'Write Python ingestion script with integrity checks.',
    priority: 'critical',
    deadline: '2026-10-06',
    estimatedHours: 6,
    actualHours: 4,
    status: 'In Progress',
    notes: 'Need to handle missing labels in partition 3.',
  },
  {
    id: 'pt-3',
    title: 'Design Pipeline Feature Extractor Class',
    description: 'Implement reusable scikit-learn compatible transformer class.',
    priority: 'high',
    deadline: '2026-10-12',
    estimatedHours: 5,
    actualHours: 0,
    status: 'To Do',
  },
  {
    id: 'pt-4',
    title: 'Setup GPU Cluster Environment & Weights & Biases Logging',
    description: 'Configure PyTorch 2.x, CUDA drivers, and experiment tracking dashboard.',
    priority: 'medium',
    deadline: '2026-10-14',
    estimatedHours: 3,
    actualHours: 0,
    status: 'Backlog',
  },
  {
    id: 'pt-5',
    title: 'Train ResNet / BERT Hybrid Baseline',
    description: 'Run 50 epochs on benchmark split and save checkpoint weights.',
    priority: 'critical',
    deadline: '2026-10-28',
    estimatedHours: 12,
    actualHours: 0,
    status: 'Backlog',
  },
];

export const INITIAL_CLIENT_PROJECTS: ClientProject[] = [
  {
    id: 'cp-1',
    clientName: 'TechVlog Channel (Rahul)',
    projectName: 'AI Smartphone Review & Benchmark Edit',
    videoType: 'YouTube Long-form',
    deadline: '2026-10-01',
    status: 'Editing',
    hoursSpent: 4.5,
    payment: 12000,
    currency: 'INR',
    revisionCount: 0,
    notes: 'Include fast-paced B-roll transitions, sound effects, and color grading.',
  },
  {
    id: 'cp-2',
    clientName: 'Fitness Pro Academy',
    projectName: 'Instagram Reel Campaign (3x Reels)',
    videoType: 'Reel/Short',
    deadline: '2026-10-08',
    status: 'Backlog',
    hoursSpent: 1.0,
    payment: 7500,
    currency: 'INR',
    revisionCount: 0,
    notes: 'Hook in first 1.5 seconds, animated subtitles with bold highlights.',
  },
  {
    id: 'cp-3',
    clientName: 'Startup Showcase',
    projectName: 'Product Launch Teaser Promo (60s)',
    videoType: 'Commercial Ad',
    deadline: '2026-10-18',
    status: 'Backlog',
    hoursSpent: 0,
    payment: 15000,
    currency: 'INR',
    revisionCount: 0,
    notes: 'Cyberpunk aesthetic, 3D text tracking.',
  },
];

export const INITIAL_HABITS: Habit[] = [
  {
    id: 'h-1',
    name: 'DSA 2-Hour Daily Practice',
    targetDescription: 'Minimum 2 hours solving problems',
    iconName: 'Brain',
    daysSchedule: ['daily'],
    streak: 24,
    bestStreak: 32,
    completions: {
      '2026-09-24': true,
      '2026-09-25': true,
      '2026-09-26': true,
      '2026-09-27': false,
    },
  },
  {
    id: 'h-2',
    name: 'Data Science Study (1.5h)',
    targetDescription: 'CodeWithHarry course & exercises',
    iconName: 'BarChart3',
    daysSchedule: ['daily'],
    streak: 18,
    bestStreak: 20,
    completions: {
      '2026-09-24': true,
      '2026-09-25': true,
      '2026-09-26': true,
      '2026-09-27': false,
    },
  },
  {
    id: 'h-3',
    name: 'Web Dev Mastery (1h)',
    targetDescription: 'Strengthening full-stack skills',
    iconName: 'Code2',
    daysSchedule: ['daily'],
    streak: 12,
    bestStreak: 15,
    completions: {
      '2026-09-24': true,
      '2026-09-25': true,
      '2026-09-26': false,
      '2026-09-27': false,
    },
  },
  {
    id: 'h-4',
    name: 'Major Project Development',
    targetDescription: 'Daily 1-2 hours sprint progress',
    iconName: 'Rocket',
    daysSchedule: ['daily'],
    streak: 9,
    bestStreak: 14,
    completions: {
      '2026-09-24': true,
      '2026-09-25': true,
      '2026-09-26': true,
      '2026-09-27': false,
    },
  },
  {
    id: 'h-5',
    name: 'Placement & Exam Sprint Prep',
    targetDescription: 'Targeted aptitude & company revision',
    iconName: 'Briefcase',
    daysSchedule: ['daily'],
    streak: 6,
    bestStreak: 10,
    completions: {
      '2026-09-24': true,
      '2026-09-25': true,
      '2026-09-26': true,
      '2026-09-27': false,
    },
  },
  {
    id: 'h-6',
    name: '8-Hour Sleep Target',
    targetDescription: 'Protect 8h recovery & mental clarity',
    iconName: 'Moon',
    daysSchedule: ['daily'],
    streak: 15,
    bestStreak: 25,
    completions: {
      '2026-09-24': true,
      '2026-09-25': true,
      '2026-09-26': true,
      '2026-09-27': false,
    },
  },
  {
    id: 'h-7',
    name: 'Gym Workout (2h)',
    targetDescription: 'Mon, Tue, Thu, Fri strength & conditioning',
    iconName: 'Dumbbell',
    daysSchedule: ['monday', 'tuesday', 'thursday', 'friday'],
    streak: 8,
    bestStreak: 16,
    completions: {
      '2026-09-22': true,
      '2026-09-24': true,
      '2026-09-25': true,
      '2026-09-27': false,
    },
  },
  {
    id: 'h-8',
    name: 'Cricket Practice',
    targetDescription: 'Saturday & Sunday weekend match / nets',
    iconName: 'Activity',
    daysSchedule: ['saturday', 'sunday'],
    streak: 4,
    bestStreak: 8,
    completions: {
      '2026-09-20': true,
      '2026-09-26': true,
      '2026-09-27': false,
    },
  },
];

export const INITIAL_CALENDAR_EVENTS: CalendarEvent[] = [
  { id: 'ev-1', title: 'Physics Wallah Recruitment Exam', category: 'placement', date: '2026-10-03', startTime: '10:00', endTime: '13:00', description: 'Teaching Staff & Content Specialist Exam' },
  { id: 'ev-2', title: 'Course Exam 1 (Statistical Inference)', category: 'academic', date: '2026-10-05', startTime: '09:30', endTime: '12:30', description: 'Room 304, Academic Block' },
  { id: 'ev-3', title: 'Course Exam 2 (Advanced Machine Learning)', category: 'academic', date: '2026-10-07', startTime: '09:30', endTime: '12:30', description: 'Room 304, Academic Block' },
  { id: 'ev-4', title: 'L&T Placement Comprehensive Exam', category: 'placement', date: '2026-10-12', startTime: '11:00', endTime: '14:30', description: 'Aptitude + Tech Round Online Portal' },
  { id: 'ev-5', title: 'MOOCs Final Certification Exam', category: 'academic', date: '2026-10-16', startTime: '14:00', endTime: '17:00', description: 'NPTEL Proctored Center' },
  { id: 'ev-6', title: 'Major Semester Project Final Defense', category: 'project', date: '2026-11-27', startTime: '10:00', endTime: '12:00', description: 'Department Auditorium Presentation' },
  { id: 'ev-7', title: 'MTech Department Classes', category: 'academic', date: '2026-09-28', startTime: '09:00', endTime: '11:00', description: 'Monday 2h Lecture' },
  { id: 'ev-8', title: 'Gym Workout Session', category: 'health', date: '2026-09-28', startTime: '17:30', endTime: '19:30', description: 'Chest & Triceps' },
  { id: 'ev-9', title: 'Cricket Match Practice', category: 'health', date: '2026-09-27', startTime: '16:00', endTime: '18:30', description: 'Sunday practice session at University ground' },
  { id: 'ev-10', title: 'TechVlog Video Delivery Deadline', category: 'client', date: '2026-10-01', startTime: '18:00', endTime: '19:00', description: 'Submit v1 cut for review' },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 't-1',
    title: 'Physics Wallah: Solve 40 Physics & Pedagogy Practice Questions',
    description: 'Target Kinematics, Thermodynamics, and Electrostatics conceptual questions.',
    category: 'Placement',
    priority: 'critical',
    status: 'in_progress',
    dueDate: '2026-09-27',
    estimatedMinutes: 90,
    actualMinutes: 45,
    notes: 'PW exam is on Oct 3 - highest phase priority!',
    isPriorityTop3: true,
  },
  {
    id: 't-2',
    title: 'DSA: Solve 2 LeetCode Medium Graphs Problems (Topological Sort)',
    description: 'Course Schedule I & II + cycle detection in directed graphs.',
    category: 'DSA',
    priority: 'high',
    status: 'todo',
    dueDate: '2026-09-27',
    estimatedMinutes: 120,
    actualMinutes: 0,
    notes: 'Maintain the 2h daily DSA streak uninterrupted.',
    isPriorityTop3: true,
  },
  {
    id: 't-3',
    title: 'Major Project: Complete Dataset Extraction and Clean Missing Columns',
    description: 'Process batch 1 data and write script for batch normalization.',
    category: 'Major Project',
    priority: 'critical',
    status: 'todo',
    dueDate: '2026-09-27',
    estimatedMinutes: 90,
    actualMinutes: 0,
    notes: '2-Month Semester Project deadline: Nov 27, 2026.',
    isPriorityTop3: true,
  },
  {
    id: 't-4',
    title: 'Data Science: Complete CodeWithHarry Lecture 24 on Random Forests',
    description: 'Watch lecture, implement ensemble voting classifier in Jupyter.',
    category: 'Data Science',
    priority: 'high',
    status: 'todo',
    dueDate: '2026-09-27',
    estimatedMinutes: 75,
    actualMinutes: 0,
    notes: 'Add key hyperparameter notes to notion.',
  },
  {
    id: 't-5',
    title: 'Web Dev: Revise Next.js 15 Server Actions & Optimistic Updates',
    description: 'Quick 45m code review and pattern memorization.',
    category: 'Web Development',
    priority: 'medium',
    status: 'todo',
    dueDate: '2026-09-27',
    estimatedMinutes: 45,
    actualMinutes: 0,
  },
  {
    id: 't-6',
    title: 'L&T Prep: Practice 25 Quantitative Aptitude Questions (Percentages & Ratios)',
    description: 'Speed test: Aim for under 1.2 minutes per question.',
    category: 'Placement',
    priority: 'high',
    status: 'todo',
    dueDate: '2026-09-27',
    estimatedMinutes: 45,
    actualMinutes: 0,
  },
  {
    id: 't-7',
    title: 'Client Work: Edit First 3 Minutes of TechVlog Video',
    description: 'Sync audio, insert b-roll markers, add initial sound design.',
    category: 'Client Work',
    priority: 'medium',
    status: 'todo',
    dueDate: '2026-09-27',
    estimatedMinutes: 60,
    actualMinutes: 0,
  },
  {
    id: 't-8',
    title: 'Sunday Cricket Practice at University Ground',
    description: 'Batting nets and fielding drills (4:00 PM - 6:30 PM)',
    category: 'Health & Fitness',
    priority: 'medium',
    status: 'todo',
    dueDate: '2026-09-27',
    estimatedMinutes: 150,
    actualMinutes: 0,
  },
];

export const INITIAL_LT_QUESTION_LOGS: LTQuestionLog[] = [
  { id: 'ltq-1', section: 'quantitative_aptitude', topic: 'Percentages & Profit Loss', attempted: 45, correct: 38, accuracy: 84.4, revisionRequired: false, updatedAt: '2026-09-25' },
  { id: 'ltq-2', section: 'quantitative_aptitude', topic: 'Time, Speed & Distance', attempted: 30, correct: 21, accuracy: 70.0, revisionRequired: true, notes: 'Revise relative speed and train crossing formulas', updatedAt: '2026-09-24' },
  { id: 'ltq-3', section: 'quantitative_aptitude', topic: 'Probability & Combinatorics', attempted: 35, correct: 26, accuracy: 74.3, revisionRequired: true, notes: 'Revise circular permutations and dice combinations', updatedAt: '2026-09-25' },
  { id: 'ltq-4', section: 'logical_reasoning', topic: 'Coding Decoding & Series', attempted: 50, correct: 46, accuracy: 92.0, revisionRequired: false, updatedAt: '2026-09-26' },
  { id: 'ltq-5', section: 'logical_reasoning', topic: 'Blood Relations & Directions', attempted: 40, correct: 36, accuracy: 90.0, revisionRequired: false, updatedAt: '2026-09-23' },
  { id: 'ltq-6', section: 'logical_reasoning', topic: 'Puzzles & Seating Arrangement', attempted: 25, correct: 17, accuracy: 68.0, revisionRequired: true, notes: 'Practice 2-variable circular tables', updatedAt: '2026-09-26' },
  { id: 'ltq-7', section: 'verbal', topic: 'Reading Comprehension & Para Jumbles', attempted: 30, correct: 25, accuracy: 83.3, revisionRequired: false, updatedAt: '2026-09-22' },
  { id: 'ltq-8', section: 'technical', topic: 'Python, SQL & DBMS Fundamentals', attempted: 60, correct: 54, accuracy: 90.0, revisionRequired: false, updatedAt: '2026-09-26' },
  { id: 'ltq-9', section: 'technical', topic: 'Machine Learning & Statistics', attempted: 40, correct: 35, accuracy: 87.5, revisionRequired: false, updatedAt: '2026-09-25' },
];

export const INITIAL_TIME_SESSIONS: TimeSession[] = [
  { id: 'ts-1', category: 'DSA', taskTitle: '3Sum and Sliding Window Practice', durationMinutes: 120, startTime: '09:00', endTime: '11:00', date: '2026-09-26', notes: 'Solved 2 Mediums.' },
  { id: 'ts-2', category: 'Major Project', taskTitle: 'Dataset collection and labeling script', durationMinutes: 90, startTime: '11:30', endTime: '13:00', date: '2026-09-26' },
  { id: 'ts-3', category: 'Placement', taskTitle: 'Physics Wallah Physics Numerical Revision', durationMinutes: 90, startTime: '14:30', endTime: '16:00', date: '2026-09-26' },
  { id: 'ts-4', category: 'Data Science', taskTitle: 'CodeWithHarry Decision Trees Implementation', durationMinutes: 75, startTime: '19:30', endTime: '20:45', date: '2026-09-26' },
  { id: 'ts-5', category: 'Placement', taskTitle: 'Physics Wallah Pedagogy Preparation', durationMinutes: 45, startTime: '08:00', endTime: '08:45', date: '2026-09-27', notes: 'Morning focus session' },
];
